---
title: "Trends & Variations in Transportation Demand in Chicago"
author: "Amir Kazi"
date: "February 2019"
output:
  html_document: 
    code_folding: hide
---

```{r setup, include=FALSE}
library (tidyverse)
library (here)
library(scales)
library(ggrepel)
library(gtools)
library(forcats)
library(sf)
library(lubridate)  # lubridate masks object 'here' from package 'here'.
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=8, echo=FALSE, warning=FALSE, message=FALSE)
```


```{r, warning=FALSE, message=FALSE}
# READING PUBLIC TRANSPORTATION DATA
bus_trips <- read.csv (here::here("data", "bus_data.csv"))
train_trips <- read.csv (here::here("data", "train_data.csv"))

# READING WEATHER DATA
#weather_descriptions <- read.csv(here::here("data", "weather.csv"))
weather <- read.csv(here::here("data", "midway_weather.csv")) 

# READING DIVVY DATA
divvy_trips <- read.csv (here::here("data", "Divvy_Trips1.csv"))

# CREATING PUBLIC TRANSPORTATION DATAFRAME
train_trips$date <- ymd(train_trips$date)
train_trips$dayofweek <- lubridate::wday(train_trips$date, label=TRUE)  
train_trips$day <- day(train_trips$date)
train_trips$month <- lubridate::month(train_trips$date, label = TRUE)
train_trips$year <- year(train_trips$date)

bus_trips$date <- ymd(bus_trips$date)
bus_trips$dayofweek <- lubridate::wday(bus_trips$date, label=TRUE)  
bus_trips$day <- day(bus_trips$date)
bus_trips$month <- lubridate::month(bus_trips$date, label = TRUE)
bus_trips$year <- year(bus_trips$date)

train_trips$trip_identity = 'train'
bus_trips$trip_identity = 'bus'

train_trips$route = NA
bus_trips$station_id = NA
bus_trips$stationname = NA

public_transport = rbind(train_trips,bus_trips)
public_transport = filter (public_transport, year(date) != 2018 )

public_transport$dayofweek <- factor(public_transport$dayofweek, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))

# SETTING WEATHER DATAFRAME
weather$date <- ymd(weather$DATE)
weather$dayofweek <- lubridate::wday(weather$DATE, label=TRUE)  
weather$day <- day(weather$DATE)
weather$month <- lubridate::month(weather$DATE, label = TRUE)
weather$year <- year(weather$DATE)
weather$dayofyear <- yday(weather$DATE)
```


```{r, warning=FALSE, message=FALSE}
# MY THEME

my_theme <- 
  theme(
    axis.text = element_text(size = 7, face = "bold", family="Courier"),
    axis.title =  element_text(size = 10, face = "bold", family="Courier"),
    plot.title = element_text(hjust = 0, size = 14, face = "bold", family="Courier"), 
    plot.subtitle = element_text(size = 12, face = "bold", family="Courier"),
    plot.caption = element_text(size = 8, face = "bold", family="Courier"),
    legend.title=element_blank(),
    legend.spacing.x = unit(0.2, 'cm'),
    panel.border = element_rect(colour = "#969696", fill=NA, size=2),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())
    

# CHOOSING COLOURS FOR TYPE OF TRANSPORTATION
taxi_color <- "#fec44f"  #yellow
divvy_color <- "#6baed6" #blue
bus_color <- "#1B9969" #green
train_color <- "#c51b8a" #violet
winter_color <- "#7a859f"
divvy_female_color <- "#2171b5"
divvy_male_color <- "#6baed6"
```


# PLOT 1: Variation in demand between 2015 - 2017

```{r, warning=FALSE, message=FALSE}
# GETTING TAXI START TIMESTAMPS
taxi_2015 <- read.csv (here::here("data", "2015_Taxi_Trips1.csv"))[,1]
taxi_2016 <- read.csv (here::here("data", "2016_Taxi_Trips1.csv"))[,1]
taxi_2017 <- read.csv (here::here("data", "2017_Taxi_Trips1.csv"))[,1]

taxi_start_times <- mdy_hms(fct_c(taxi_2015, taxi_2016, taxi_2017))
taxi_start_times_date <- as.data.frame(date(taxi_start_times))

colnames(taxi_start_times_date) <- c("date")
remove(taxi_2015, taxi_2016, taxi_2017)


# PUBLIC TRANSPORTATION DEMAND GROUPED BY DAY
public_transport_by_day <-
  public_transport %>%
    group_by(date, trip_identity) %>%
    summarise(riders = sum(rides)) %>%
    select(date, riders, trip_identity)


# DIVVY DEMAND GROUPED BY DAY
divvy_trips$date <- mdy_hms(divvy_trips$START.TIME)

divvy_by_day <-
  divvy_trips %>%
    group_by(date = date(date)) %>%
    summarize (riders = n())

divvy_by_day$trip_identity = 'divvy'

# TAXI DEMAND GROUPED BY DAY
taxi_by_day <-
  taxi_start_times_date %>%
  filter(date != '2017-08-01') %>%
    group_by(date = date) %>%
    summarize (riders = n())

taxi_by_day$trip_identity = 'taxi'

# MERGED DATAFRAME OF TRANSPORTATION
total_demand_by_day <- bind_rows(public_transport_by_day,divvy_by_day, taxi_by_day)
remove(divvy_by_day, public_transport_by_day, taxi_by_day)
```

```{r, warning=FALSE, message=FALSE}
# PLOTTING GRAPH of 3 Year Chicago Public Transportation Trend + Weather


# WINTER
# Shading Winters From 21st December to 30th March
# Reference: https://stackoverflow.com/questions/18419628/creating-custom-legends-in-ggplot2

df<-data.frame(xmin=as.Date(c('2015-01-01','2015-12-21','2016-12-21', '2017-12-21' )),
               xmax=as.Date(c('2015-03-20','2016-03-30', '2017-03-30', '2017-12-31' )),
               ymin=c(-Inf,-Inf),
               ymax=c(Inf,Inf),
               winters=c("Winters"))


total_demand_by_day %>%
  ggplot(aes(x = date, y = riders/1000)) +
  geom_smooth(aes(color = trip_identity), se = FALSE, na.rm = TRUE) +
  geom_rect(data=df,aes(xmin=xmin,ymin=ymin,xmax=xmax,ymax=ymax, fill = 'winters'),
                    alpha=0.15,inherit.aes=FALSE, fill = winter_color) + 
  scale_color_manual(values=c(bus_color,divvy_color, taxi_color, train_color)) +
  scale_x_date(date_labels = "%d %b %Y") +
  theme_bw() +
  my_theme +
  theme(legend.position="none") +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = as.Date(c("2015-01-01", "2016-01-01", "2017-01-01", "2018-01-01")), 
             linetype = 4)  +
  annotate("label", x = as.Date("2015-06-01"), y = 500, 
           label = 'TRAIN', color = train_color, fontface =2,  family="Courier")  +
  annotate("label", x = as.Date("2016-06-01"), y = 670, 
           label = 'BUS', color = bus_color, fontface =2,  family="Courier") +
  annotate("label", x = as.Date("2016-06-01"), y = 100, 
           label = 'TAXI', color = taxi_color, fontface =2,  family="Courier") +
  annotate("label", x = as.Date("2015-05-01"), y = 40, 
           label = 'DIVVY', color = divvy_color, fontface =2,  family="Courier")  +
  annotate("label", x = as.Date("2016-03-21"), y = 320, 
           label = 'WINTER', color = winter_color, fontface =2,  family="Courier") +
  labs(title ="Demand for Public Transport & Divvy In Chicago Is Lowest In Winter", 
     subtitle = "Taxi Usage Less Elastic To Seasonal Changes",
     x = "", y = "Passengers Per Day (Thousands)",
     caption = "CTA Ridership Data\n 2015-2017\n *Taxi Data till July 2017") 
```




# PLOT 2A: Weekly distribution for Public Transport

```{r, warning=FALSE, message=FALSE}
temp <- 
  public_transport %>%
    group_by(dayofweek, trip_identity) %>%
    summarise(count = (sum(rides)/(3*52.19))/1000)

bus_point <-  
  temp %>%
    filter(trip_identity == "bus")

train_point <-  
  temp %>%
    filter(trip_identity == "train")
  
ggplot()  +
  geom_point(data = bus_point, aes(x = dayofweek, y = count), colour = bus_color, size = 5, stroke = 1) + 
  geom_point(data = train_point, aes(x = dayofweek, y = count), colour = train_color, size = 5, stroke = 1) + 
  geom_line(data = temp, mapping = aes(x = dayofweek, y=count),  alpha = 0.3)  +
  scale_y_continuous(labels = scales::comma) +
  coord_cartesian( ylim = c(200, 900)) + 
  labs(title ="Usage of Public Transport in Chicago is Highest on Weekdays", 
       subtitle = "Weekends see a significant drop in riders",
       x = "Day of Week", y = "Average Daily Passengers (Thousands)",
       caption = "CTA Ridership Data\n 2015-2017") +
  theme_bw()  + 
  theme(plot.title = element_text(hjust = -0, size = 12, face = "bold"), 
        plot.subtitle = element_text(size = 10, face = "bold"), 
        legend.title=element_blank(),
        legend.key = element_rect(fill = "white")) +
  coord_flip() +
  my_theme + 
  annotate("label", x = 5.5, y = 370, 
         label = 'TRAIN', color = train_color, fontface =2,  family="Courier") + 
  annotate("label", x = 6.5, y = 510, 
         label = 'BUS', color = bus_color, fontface =2,  family="Courier") + 
  theme(legend.position="none",
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank()
        )
```


# PLOT 2B: Weekly distribution for Taxis & Divvy

```{r, warning=FALSE, message=FALSE}

taxi_num_days <- n_distinct(date(taxi_start_times_date$date))
divvy_num_days <- n_distinct(date(divvy_trips$date))

taxi_start_times_date$hour <- hour(taxi_start_times_date$date)
taxi_start_times_date$weekday <- lubridate::wday(taxi_start_times_date$date, label = TRUE)

taxi_by_weekday <-
  taxi_start_times_date %>%
    group_by(weekday) %>%
    summarise(count = n())

divvy_by_weekday <-
  divvy_trips %>%
  group_by(weekday = wday(divvy_trips$date)) %>%
  summarize(count = n())

taxi_by_weekday$weekday <- factor(taxi_by_weekday$weekday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))

ggplot()  +
  geom_point(data = taxi_by_weekday, aes(x = weekday, y = count/taxi_num_days), 
             colour = taxi_color, size = 5, stroke = 1)+
  geom_point(data = divvy_by_weekday, aes(x = weekday, y = count/divvy_num_days), 
             colour = divvy_color, size = 5, stroke = 1) +
  scale_y_continuous(labels = scales::comma) +
  #coord_cartesian( ylim = c(200, 900)) + 
  labs(title ="Taxi Demand Peaks Throughout Week, Then Falls On Weekend", 
       subtitle = "Divvy Bike Demand Remains Constant",
       x = "Day of Week", y = "Average Daily Trips",
       caption = "Chicago Taxi & Divvy \n Ridership Data 2015-2017") +
  theme_bw()  + 
  theme(plot.title = element_text(hjust = -0, size = 12, face = "bold"), 
        plot.subtitle = element_text(size = 10, face = "bold"), 
        legend.title=element_blank(),
        legend.key = element_rect(fill = "white")) +
  coord_flip() +
  my_theme + 
  annotate("label", x = 5, y = 7700, 
         label = 'TAXI', color = taxi_color, fontface =2,  family="Courier") + 
  annotate("label", x = 5, y = 2210, 
         label = 'DIVVY', color = divvy_color, fontface =2,  family="Courier") + 
  theme(legend.position="none",
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank()
        )

```




# PLOT 3: Public Transport Demand Variation in Winter on snow days and non-snow days

```{r, warning=FALSE, message=FALSE}

winter_dates <- 
  weather %>%
  filter((date >= "2015-01-01" & date <= "2015-03-20") |
           (date >= "2015-12-21" & date <= "2016-03-20") |
           (date >= "2016-12-21" & date <= "2017-03-20") |
           (date >= "2017-12-21" & date <= "2017-12-31"))

snow_days <-
  winter_dates %>% 
  filter (SNOW > 0)

no_snow_days <-
  winter_dates %>% 
  filter (SNOW == 0)
  
train_snow_days <- 
  merge(snow_days, train_trips, by = "date") %>%
  group_by(date) %>%
  summarize (riders = sum(rides)) %>%
  mutate (type = "TRAIN", day_type = "SNOW")

train_no_snow <- 
  merge(no_snow_days, train_trips, by = "date") %>%
  group_by(date) %>%
  summarize (riders = sum(rides)) %>%
  mutate (type = "TRAIN", day_type = "NO SNOW")

bus_snow_days <- 
  merge(snow_days, bus_trips, by = "date") %>%
  group_by(date) %>%
  summarize (riders = sum(rides)) %>%
  mutate (type = "BUS", day_type = "SNOW")

bus_no_snow <- 
  merge(no_snow_days, bus_trips, by = "date") %>%
  group_by(date) %>%
  summarize (riders = sum(rides)) %>%
  mutate (type = "BUS", day_type = "NO SNOW")

snow_comparison <- do.call("rbind", list(train_snow_days, train_no_snow, bus_snow_days,bus_no_snow ))
snow_comparison$day_type <- factor(snow_comparison$day_type, levels = c("SNOW", "NO SNOW"))
remove (train_snow_days, train_no_snow, bus_snow_days,bus_no_snow, snow_days, no_snow_days)

ggplot(snow_comparison) +
  geom_boxplot(aes(x = day_type, y = riders/1000,  fill = type)) + 
  scale_x_discrete(labels = c('Rides Taken on Snow Days \n in Winter',
                              'Rides Taken on Non-Snow Days \n in Winter')) +
  labs(title ="Snow Does NOT Have Much Effect on Ridership in Winter", 
       subtitle = "Cold Non-Snowy Days Seem As Unappealing To Riders",
       x = "", 
       y = "Riders (Thousands)",
       caption = "NCEI & CTA Rider Data\n 2015-2017") +
  theme_bw() +
  my_theme +
  scale_fill_manual(values=c(bus_color, train_color)) +
  annotate("label", x = 0.8, y = 200, 
           label = 'BUS', color = bus_color, fontface =2,  family="Courier") +
  annotate("label", x = 1.8, y = 120, 
           label = 'BUS', color = bus_color, fontface =2,  family="Courier") +
  annotate("label", x = 1.2, y = 750, 
           label = 'TRAIN', color = train_color, fontface =2,  family="Courier")  +
  annotate("label", x = 2.2, y = 750, 
           label = 'TRAIN', color = train_color, fontface =2,  family="Courier") +
  theme(legend.position="none")
  
```



# PLOT 4: Bus Demand Variation - Month By Years
```{r, warning=FALSE, message=FALSE}
# reference: https://ibecav.github.io/slopegraph/

p <- public_transport %>%
  group_by(year, month, trip_identity) %>%
  summarise(riders = sum(rides)) %>%
  filter (trip_identity == "bus") 

green_palette <- c("#467563", "#78c679", "#78c679", "#238443","#467563", 
                   "#c2e699", "#78c679", "#238443","#78c679", "#78c679", "#78c679", "#238443")

alternative <- c(train_color, divvy_color, taxi_color, winter_color, 
                 "#525252", "#02818a", train_color, 
                 divvy_color, taxi_color, winter_color, "#e31a1c", "#6a51a3")

ggplot(p, aes(x = year, y = riders, group = month)) +
  scale_x_discrete(labels = c('Rides Taken on Snow Days \n in Winter',
                              'Rides Taken on Non-Snow Days \n in Winter', "wow"))  +
  geom_line(aes(color = month), alpha = 1, size = 1, linetype = 1) +
  geom_point(aes(color = month, alpha = 1), size = 1.5) + 
  scale_colour_manual(values=green_palette) +
  geom_label_repel(data = p %>% filter(year == "2015"),
                  aes(label = paste0(month), color = month, family = "Courier", fontface = 2) , 
                  hjust = "left", 
                  fontface = 7, 
                  size = 3, 
                  nudge_x = -.45, 
                  direction = "y") +
  geom_label_repel(data = p %>% filter(year == "2017"),
              aes(label = paste0(month), color = month, family = "Courier", fontface = 2) , 
              hjust = "right", 
              fontface = 7, 
              size = 2.5, 
              nudge_x = .4,
              direction = "y") +
  #scale_x_discrete(position = "bottom") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.border     = element_blank()) +
  #theme(axis.title.x     = element_blank()) +
  theme(axis.text.y     = element_blank()) +
  theme(axis.ticks   = element_blank()) +
    my_theme +
  labs( title = "Overall Bus Usage Has Declined Between 2015 and 2017",
    subtitle = "Summer Months still experience more bus usage than in Winter",
    caption = "CTA Transit Data\n 2015 - 2017",
    x = "2015                     2016                      2017",
    y = "Total Bus Riders") +
  theme(plot.title = element_text(hjust = 0.58, size = 12, face = "bold"), 
        plot.subtitle = element_text(hjust = 0.515, size = 10, face = "bold")) + 
    scale_y_continuous(labels = scales::comma) 

```

# PLOT 5: Hourly Variation in Divvy Demand by Gender

```{r, warning=FALSE, message=FALSE}

divvy_by_gender <- divvy_trips %>%
  filter(GENDER != '') %>%
  group_by(hour_of_day = hour(date), GENDER) %>%
  summarize(riders_by_hour = trunc(n() / (365*3)))


ggplot(data = divvy_by_gender) +
  geom_col(data = subset(divvy_by_gender, GENDER == "Male"), 
           aes(x = hour_of_day, y = riders_by_hour, fill = GENDER), fill = divvy_male_color) +
  geom_col(data = subset(divvy_by_gender, GENDER == "Female"), 
           aes(x = hour_of_day, y = -riders_by_hour, fill = GENDER), fill = divvy_female_color) + 
  scale_fill_brewer(palette = "Set1") + 
  theme_bw() +
  coord_flip() +
  geom_hline(yintercept=0, colour="white", lwd=1) + my_theme + 
  scale_y_continuous( labels = abs) +
  annotate("label", x = 23.5, y = -140,
           label = 'FEMALE RIDERS', color = divvy_female_color, fontface =2,  family="Courier") +
  annotate("label", x = 23.50, y = 250, 
           label = 'MALE RIDERS', color = divvy_male_color, fontface =2,  family="Courier") +
  labs(title ="Highest Demand For Divvy Bikes During Peak Morning & Evening Hours", 
     subtitle = "Significantly Fewer Female Riders, Especially At Night",
     x = "", y = "Passengers Per Day",
     caption = "Divvy Ridership Data\n 2015-2017") + 
  scale_x_continuous(sec.axis = dup_axis(), breaks = c(0,6,12,17,22), 
                     labels = c("Midnight", "6 am", "Noon", "5 pm", "10 pm" )) +
  theme(axis.title.x = element_text(hjust = 0.2))

#remove(divvy_by_gender)
```

# PLOT 6: Taxi Heat Map
```{r, warning=FALSE, message=FALSE}
# GETTING TAXI START TIMESTAMPS
#taxi_2015 <- read.csv (here::here("data", "2015_Taxi_Trips1.csv"))[,1]
#taxi_2016 <- read.csv (here::here("data", "2016_Taxi_Trips1.csv"))[,1]
#taxi_2017 <- read.csv (here::here("data", "2017_Taxi_Trips1.csv"))[,1]

#taxi_start_times <- mdy_hms(fct_c(taxi_2015, taxi_2016, taxi_2017))
taxi_start_times_solo <- as.data.frame(taxi_start_times)
#colnames(taxi_start_times_date) <- c("date")
#remove(taxi_2015, taxi_2016, taxi_2017)

taxi_light <- "#ffffb2"
taxi_dark <- "#cc4c02"

taxi_start_times_solo$hour <- hour(taxi_start_times_solo$taxi_start_times)
taxi_start_times_solo$weekday <- lubridate::wday(taxi_start_times_solo$taxi_start_times, label = TRUE)

taxi_by_hour <-
  taxi_start_times_solo %>%
  group_by(weekday, hour) %>%
  summarize(count = n())

taxi_by_hour$weekday <- factor(taxi_by_hour$weekday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
taxi_by_hour$hour <- as.factor (taxi_by_hour$hour)
taxi_by_hour$hour <- factor(taxi_by_hour$hour, 
                            levels = rev(c("0", "1","2", "3","4", "5","6", "7","8", "9","10", 
                                           "11","12", "13","14", "15","16", 
                                       "17","18", "19",
                                       "20", "21","22", "23")))


ggplot(data = taxi_by_hour, aes(x = weekday, y = hour,  fill = count/taxi_num_days)) +
  geom_tile() +
  scale_fill_gradient(low = taxi_light, high = taxi_dark,name = "Taxi Trips", labels = comma) +
  theme_bw() +
  my_theme + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +  
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(vjust=-1.3),
        axis.text.x = element_text(size = 8, face = "bold")) +
  theme (legend.key = element_rect(fill = "black"),
        legend.spacing.x = unit(0.2, 'cm'),
        legend.text = element_text(family = "Courier", size = 8, face = "bold"),
        legend.title = element_text(family = "Courier", size = 8, face = "bold"),
        legend.background = element_rect(fill="white", size=1, linetype="solid",colour ="#969696")) +
  scale_x_discrete (position = "top", expand = c(0,0)) +
  scale_y_discrete(breaks = c(0,3,6,9,12,15,18,21),
                   labels = c("Midnight","3 am","6 am","9 am", "Noon", "3 pm", "6 pm", "9 pm"))  +
  labs (title ="Highest Weekday Taxi Traffic Between 6-8 pm, Much Later on Weekends", 
       subtitle = "Weekend Rush Drives Taxis Late Into The Night",
       x = "", 
       y = "",
       caption = "Chicago Taxi Trips Data\n 2015-2017") 
```
  
```{r}
# Physical Manifestations of Seasonal Changes
# SNOW & PRECIPITATION LEVELS CHANGE

weather %>%
  group_by(month) %>%
  summarize(avg_prcp = mean(PRCP, na.rm = TRUE), avg_snow = mean(SNOW, na.rm = TRUE)) %>%
  ggplot() +
  geom_step(aes(x = month, y = avg_prcp, group = 1), colour = "cyan4") +
  geom_step(aes(x = month, y = avg_snow, group = 1), colour = "indianred1") +
  theme_bw() + 
  annotate(geom="text", x=3.55, y=7, label="SNOW", color="indianred3", fontface =4) +
  annotate(geom="text", x=7, y=4.9, label="PRECIPITATION", color="cyan4", fontface =4) +
  labs(title ="Larger Seasonal Variation in Snow than in Precipitation in Chicago", 
       subtitle = "Precipitation Slightly Higher During Summer ",
       x = "", 
       y = "Monthly Average (Inches)",
       caption = "National Centers for\n Environmental Information 2015-2017") +
  my_theme +
  annotate("label", x=3.55, y=7,
           label = 'SNOW', color = train_color, fontface =2,  family="Courier") +
  annotate("label", x=7, y=4.9,
           label = 'PRECIPITATION', color = train_color, fontface =2,  family="Courier") 

```



